---
title: "Dépanner les bases de données sur mesure"
permalink: "error-handling"
'description': "Décrit comment gérer les erreurs et résoudre les problèmes lors de l’utilisation de votre base de données en tant que fournisseur d’identité."
'og:title': "Dépanner les bases de données sur mesure"
'og:description': "Décrit comment gérer les erreurs et résoudre les problèmes lors de l’utilisation de votre base de données en tant que fournisseur d’identité."
'og:image': "https://cdn2.auth0.com/docs/1.14567.0/img/share-image.png"
'twitter:title': "Dépanner les bases de données sur mesure"
'twitter:description': "Décrit comment gérer les erreurs et résoudre les problèmes lors de l’utilisation de votre base de données en tant que fournisseur d’identité."
---

Vous pouvez retourner les erreurs résultant de votre connexion à la base de données personnalisée à des fins de dépannage. Nous aborderons également quelques étapes de dépannage de base pour vos scripts.

## Types of errors (Types d’erreurs)

Vous pouvez recevoir différents types d’erreurs lors d’une connexion à une base de données :

<table class="table"><thead>
<tr>
<th>Erreur</th>
<th>Script de connexion</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>`new WrongUsernameOrPasswordError(&lt;email or user_id&gt;, &lt;message&gt;)`</td>
<td>Connexion</td>
<td>Se produit lorsque les identifiants de l’utilisateur ne sont pas valides. Si aucun argument n’est fourni ou si le premier argument est erroné, l’erreur sera enregistrée comme un événement `fu` (nom d’utilisateur ou courriel invalide) avec une chaîne vide comme `user_id`. Fournir un premier argument véridique résultera en un événement `fp` (l’utilisateur existe, mais le mot de passe est invalide) avec une valeur `user_id` de `auth0|&lt;premier argument&gt;`. Pour en savoir plus, consultez <a href="/docs/fr-ca/deploy-monitor/logs/log-event-type-codes">Codes de type d’événement de journal</a>.</td>
</tr>
<tr>
<td>`new ValidationError(&lt;user_exists&gt;, &lt;message&gt;)`</td>
<td>Créer</td>
<td>Se produit lorsqu’un utilisateur existe déjà dans votre base de données.</td>
</tr>
<tr>
<td>`callback(&lt;null&gt;,&lt;false&gt;)`</td>
<td>Modifier le mot de passe</td>
<td>Se produit lorsque le mot de passe de l’utilisateur n’a pas été mis à jour.</td>
</tr>
<tr>
<td>`callback(&lt;null&gt;)`</td>
<td>Obtenir l’utilisateur</td>
<td>Se produit lorsque l’utilisateur est introuvable.</td>
</tr>
<tr>
<td>`new UnauthorizedError(&lt;message&gt;)`</td>
<td>Tous les scripts de connexion</td>
<td>Se produit lorsque quelque chose n’a pas fonctionné lors de la tentative d’accès à la base de données. C’est le moyen préféré de communiquer les erreurs depuis les bases de données personnalisées vers le système frontal.</td>
</tr>
<tr>
<td>`new Error(&lt;message&gt;)`</td>
<td>Tous les scripts de connexion</td>
<td>Se produit lorsque quelque chose n’a pas fonctionné lors de la tentative d’accès à la base de données.</td>
</tr>
<tr>
<td>`error code: auth0_idp_error; user already exists`</td>
<td>Créer</td>
<td>Se produit dans le magasin d’identité hérité lorsque vous tentez de créer un utilisateur qui existe déjà dans votre magasin d’identité hérité ou dans Auth0.</td>
</tr>
<tr>
<td>`error code: auth0_idp_error; user already exists`</td>
<td>Supprimer</td>
<td>Se produit dans l’ancien magasin d’identité lorsque vous tentez de supprimer un utilisateur avec des scripts de base de données personnalisés. L’erreur peut aussi se manifester sous la forme `Error ! Il y a eu un problème lors de la suppression de user@example.com` ou `Sandbox Error : Veuillez implémenter le script de suppression pour cette connexion à la base de données à l’adresse suivante https://manage.auth0.com/#/connections/database`.</td>
</tr>
</tbody>
</table>

## Renvoyer une erreur

Pour retourner une erreur, faites une requête à la fonction **callback** en y passant **error** comme premier paramètre :

```javascript lines
callback(error);
```

Exemple :

```javascript lines
callback(new ValidationError('email-too-long', 'Email is too long.'));
```

### Retourner des erreurs lors de l’utilisation de Lock

Si vous utilisez Lock, vous pouvez [personnaliser les messages d’erreur](/docs/fr-ca/customize/login-pages/classic-login/customize-lock-error-messages) qui seront affichés en les ajoutant au dictionnaire.

## Dépannage des erreurs

Testez le script à l’aide du bouton **Try** (Essayer).

Si vous n’avez pas obtenu le résultat attendu, ou recevez un message d’erreur, installez l’extension [Real-time Webtask Logs](/docs/fr-ca/customize/extensions/real-time-webtask-logs), utilisez des énoncés `console.log()` dans votre script et essayez la connexion à nouveau. Le résultat de `console.log()` s’imprime dans la fenêtre Real-time Webtask Logs (Journaux Webtask en temps réel).

Des erreurs peuvent survenir lors de l’utilisation de scripts d’action pour importer, créer ou supprimer des utilisateurs. Utilisez des énoncés `console.logs` pour vérifier que l’erreur résulte de l’utilisation de scripts d’action. Pour en apprendre davantage, lisez [Modèles de scripts d’actions de base de données personnalisés](/docs/fr-ca/authenticate/database-connections/custom-db/templates).